# Configuración de seguridad Apache
ServerTokens Prod
ServerSignature Off
TraceEnable Off
FileETag None

# Timeouts
Timeout 60
KeepAlive On
MaxKeepAliveRequests 100
KeepAliveTimeout 5

# Limitaciones
LimitRequestBody 1073741824
LimitXMLRequestBody 1073741824
