<?php

/**
 * Implements hook_preprocess_page().
 */
function menu_breadcrumb_custom_preprocess_page(array &$variables): void {
  // No afectar el admin.
  $path = \Drupal::service('path.current')->getPath();
  if (str_starts_with($path, '/admin')) {
    return;
  }

  /** @var \Drupal\menu_breadcrumb_custom\MenuBreadcrumbBuilder $builder */
  $builder = \Drupal::service('menu_breadcrumb_custom.builder');
  $variables['menu_breadcrumb'] = $builder->buildRenderArray();
}
